### ISSUE TITLE
New CCD data?

### ISSUE THREAD

**Issue by dcaud** [UrbanInstitute/education-data-package-r#106]
Hi!

It looks like new data are available for 2021-2022 in the CCD:

https://nces.ed.gov/ccd/files.asp#Fiscal:2,LevelId:7,SchoolYearId:36,Page:1 

Do you know when these will be available thru the urbanInstitute's API?

**Comment by erika-tyagi** [comment]
Hi @dcaud - sorry for missing this earlier! The new data is up, and we added a tentative updates schedule to the portal documentation [here](https://educationdata.urban.org/documentation/#data_update). You can also sign up for the portal newsletter [here](https://www.tfaforms.com/4644066?tfa_1927=EDD) to get notifications in your inbox when new data is available through the API. You can also reach out to the research team that manages the data processing and release schedule directly at educationdata@urban.org.
