### ISSUE TITLE
Codebooks For Data?

### ISSUE THREAD

**Issue by blackholeboi** [UrbanInstitute/education-data-package-r#120]
Hello,

I'm having trouble finding codebooks for the data to interpret certain things. At the moment, the biggest issue is the school's financial data.  Some of the entries have "-2" or "1" values when there are usually dollar amounts. When I look at the data notes/appendices/survey questions listed on CRDC's website, none of that information is available.

I'm also having issues with the demographic information.  Race and sex are just numbers.  I can't find any information with the source data about what these numbers are meant to be.  I tried looking up a school on the NCES website, but it appears that the demographic data is more recent, so I'm not sure I can even reliably infer which is which.

Any help would be appreciated.

**Comment by erika-tyagi** [comment]
Thanks for reaching out! The best place to find codebooks and metadata is from the Education Data Portal documentation site, for example here for CRDC school finance data: https://educationdata.urban.org/documentation/schools.html#crdc_school-finance. 

This documentation site provides information on the harmonized encoding that we perform (e.g. so -2 = Not applicable, -1 = Missing/not reported, etc.) before publishing the data. You can also download codebooks at Excel files from the site. 

Feel free to reach out if you run into issues using this data or R package - thanks!
