### ISSUE TITLE
Issue with API documentation

### ISSUE THREAD

**Issue by jrisi256** [UrbanInstitute/education-data-package-r#59]
Hello! Thanks for making such a great package. I know it's in beta and all. I just wanted to point out a small issue with the documentation on the API.

The R example for "Enrollment—Headcount" under Colleges (IPEDS) is wrong. Currently it is:
```r
library(educationdata)
data <- get_education_data(level = "college-university",
    source = "ipeds",
    topic = "admissions-enrollment",
    filters = list(year = 2011, level_of_study = "undergraduate"))
```

It should actually be
```r
library(educationdata)
data <- get_education_data(level = "college-university",
    source = "ipeds",
    topic = "enrollment-headcount",
    filters = list(year = 2011, level_of_study = "undergraduate"))
```

**Comment by khueyama** [comment]
@jrisi256 This should be fixed now at: https://educationdata.urban.org/documentation/colleges.html#ipeds-enrollment-headcount

Thanks for catching and let me know if you need anything else!
