### ISSUE TITLE
`leaid` sometimes returned as character, sometimes as numeric

### ISSUE THREAD

**Issue by ramorel** [UrbanInstitute/education-data-package-r#63]
Not a huge problem, but there are inconsistencies in how `leaid` is returned:

```
library(tidyverse)
library(educationdata)
suppressMessages(
  get_education_data(
    level = "school-districts",
    source = "ccd",
    topic = "directory",
    filters = list(year = 2008:2015)
    )
  ) %>% 
  pull(leaid) %>% 
  class()
#> [1] "character"

suppressMessages(
  get_education_data(
    level = "school-districts",
    source = "ccd",
    topic = "enrollment",
    filters = list(year = 2008, grade = 99, fips = 1)
    )
  ) %>% 
  pull(leaid) %>% 
  class()
#> [1] "integer"
```

requiring the user to recode the variable in order to join data. Consistency in variable class would be helpful!

**Comment by khueyama** [comment]
@ramorel Thanks for flagging this! It looks like an issue with the underlying API data. I've filed an issue with the team for our next release.

**Comment by khueyama** [comment]
@ramorel I just checked your example code, and looks like this has been fixed in the latest release. Let me know if you run into anything else!
