### ISSUE TITLE
Find number of students on Pell through IPEDS?

### ISSUE THREAD

**Issue by jrisi256** [UrbanInstitute/education-data-package-r#64]
This is more a question about the API itself rather than anything technical. Is it currently possible to query the API to found out the number/percentage of total undergraduates receiving a Pell grant? I know there is graduation rate by type of financial aid received, but that's not really what I'm looking for.

**Comment by khueyama** [comment]
@jrisi256 This isn't something that is currently available in the API, but we will be including IPEDS Student Financial Aid data in a future release!

**Comment by jrisi256** [comment]
Hello! Thank you for continuing to improve this data portal. It's such a great resource. Do you have an idea of when student financial aid data might be added? Is there a public road map available anywhere?

**Comment by grahamimac** [comment]
Hi, thanks for the kind words. We do not have a release calendar yet, and we are moving along as best we can in these times (a little difficult given all that's going on, but we're making progress). We are currently planning to release this data sometime in the summer. I hope that helps.

**Comment by jrisi256** [comment]
Of course! I understand. Everything is crazy right now. If I wanted to access this data in a somewhat programmatic way right now, is there anything you could recommend? Going through the GUI for IPEDS is a bit of a nightmare.

**Comment by grahamimac** [comment]
I'm not as familiar with this, but perhaps @ericatheresa might have some ideas from her or her colleagues' work.

**Comment by ericatheresa** [comment]
Hi @jrisi256 ,
I'm sorry that the SFA data aren't up in the portal yet! We're working on it, and I appreciate your patience. The easiest way to get these data in the meantime is by downloading the complete data files (under "survey data"). The files have pretty consistent naming conventions, so you should be able to download them pretty easily through a loop. If you just want those two variables though, and only a couple of years, it might be just as easy to use the point-and-click interface to get exactly what you want. I downloaded a couple just now and am happy to email them to you; you can reach me at eblom@urban.org.
Cheers,
Erica

**Comment by jrisi256** [comment]
Of course! I imagine this is a difficult task made all the more difficult by the virus. I'm very appreciative of all the progress that's been made so far. I will check out downloading the complete data files under survey data in the mean time. I'm interested in more than just those two variables however across a range of years. Thanks for helping.
