### ISSUE TITLE
Harmonize data across years?

### ISSUE THREAD

**Issue by dcaud** [UrbanInstitute/education-data-package-r#66]
Hello. Great package. Do you have an example script, even if incomplete, that harmonizes data across years? For example, if I wanted to create a file with enrollment, for each school, for each year from 2001-2018, is there a function that handles variable renaming and re-coding over time?

**Comment by khueyama** [comment]
@dcaud The API returns harmonized data, although enrollment data for CCD is only available through 2016. Data for 2017 and 2018 should be available in a later release. You could pull enrollment data using a snippet like the following:

```
library(educationdata)
library(dplyr)

df <- educationdata::get_education_data(
  level = "schools",
  source = "ccd",
  topic = "enrollment",
  filters = list(
    year = 2001:2016,
    ncessch = c("063153004890"),
    grade = 9:12)
)
```

Note that in this case I limited myself to a single school and a range of grades for the sake of runtime. To aggregate by year and school you could then run something like:

```
df <- df %>%
  group_by(year, ncessch) %>%
  summarise(enrollment = sum(enrollment))
```

Hope this helps!

**Comment by dcaud** [comment]
Thanks so much!
