### ISSUE TITLE
Processing failure

### ISSUE THREAD

**Issue by JackLandry** [UrbanInstitute/education-data-package-r#73]
Thanks for making all this data available! 
Just started trying to use this with a basic query, but this yields the error "rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match"

`library(educationdata)

school_district_directory <- get_education_data(level = 'school-districts', 
                         source = 'ccd', 
                         topic = 'directory')`

**Comment by khueyama** [comment]
Hello @JackLandry - thank you for trying out the package, and sorry you are having issues. Our team is currently working on a fix for this error and I will let you know once that is in place. In the meantime you can try using the `csv` option, which I believe should work:

```r
library(educationdata)

school_district_directory <- get_education_data(level = 'school-districts',
                                                source = 'ccd',
                                                topic = 'directory',
                                                csv = TRUE)
```

**Comment by grahamimac** [comment]
@JackLandry It's been a busy week! The fix for this was deployed last Friday, so your original request should now work as should Kyle's workaround. I hope this helps.
