### ISSUE TITLE
New data release schedule?

### ISSUE THREAD

**Issue by cra-cerp** [UrbanInstitute/education-data-package-r#74]
(This is a question, not an issue.)

Your API has been such a valuable resource and makes accessing data so much easier than the IPEDS GUI! Do you have a sense of when you will be releasing new years of data? I'm particularly interested in the more recent years of completions-cip-2 datasets, which currently go up to 2016.

Thanks!
Evelyn

**Comment by grahamimac** [comment]
Hi Evelyn, We do not yet have a publicly available release schedule, unfortunately but this is definitely on our radar (we are continuously improving our process, but on a budget!). Our goal is to have this data updated in a few months, hopefully by late summer/early fall.

**Comment by cra-cerp** [comment]
Thanks so much! I'll keep an eye out for it later this year.

Our Center is using the data you've made available to make a web app that supports computing departments across the US in easily accessing their own statistics when they apply for NSF funding. So thanks for the work you are doing!
